spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stadtverwaltung
    username: stadtverwaltung
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  main:
    allow-bean-definition-overriding=true: